name: flutter_day_94_todo
description: An example todos app that showcases bloc state management patterns.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # state_management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # i18n & l10n
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.8

  # app_packages
  local_storage_todos_api:
    path: packages/local_storage_todos_api
  todos_api:
    path: packages/todos_api
  todos_repository:
    path: packages/todos_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  bloc_test: ^9.1.7
  mockingjay: ^0.5.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  generate: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
