name: todos_api
description: The interface and models for an API providing access to todos.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  meta: ^1.12.0
  uuid: ^4.4.2

dev_dependencies:
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  test: ^1.21.4